import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dancingScript = localFont({
  src: [
    {
      path: "../Fonts/dancingScript-regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../Fonts/dancingScript-bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../Fonts/dancingScript-semiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../Fonts/dancingScript-medium.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-dancingScript",
});

const bilmond = localFont({
  src: [
    {
      path: "../Fonts/bilmond-thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../Fonts/bilmond-extralight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../Fonts/bilmond-light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../Fonts/bilmond-regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../Fonts/bilmond-medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../Fonts/bilmond-semibold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../Fonts/bilmond-bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../Fonts/bilmond-black.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../Fonts/bilmond-extrablack.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-bilmond",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`
        ${geistSans.variable}
        ${geistMono.variable}
        ${bilmond.variable}
        ${dancingScript.variable}
        h-full antialiased
      `}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
